### ISSUE TITLE
ModuleNotFoundError: No module named 'Crypto'

### ISSUE THREAD

**Issue by dobrynski** [Arnie97/chrome-cookiejar#2]
I've tried crypto, pycrypto, pycryptodomex and I think a few others but I always get:

```
Traceback (most recent call last):
  File "/Users/michal/PycharmProjects/echo360dl/test.py", line 1, in <module>
    from chrome_cookiejar import ChromeCookieJar
  File "/Users/michal/PycharmProjects/echo360dl/chrome_cookiejar/__init__.py", line 1, in <module>
    from .main import ChromeCookieJar  # NoQA
  File "/Users/michal/PycharmProjects/echo360dl/chrome_cookiejar/main.py", line 5, in <module>
    from .decrypt import decrypt
  File "/Users/michal/PycharmProjects/echo360dl/chrome_cookiejar/decrypt.py", line 10, in <module>
    from .unix_crypt import aes_cbc_decrypt, get_chrome_safe_storage
  File "/Users/michal/PycharmProjects/echo360dl/chrome_cookiejar/unix_crypt.py", line 1, in <module>
    from Crypto.Cipher import AES
ModuleNotFoundError: No module named 'Crypto'
```

**Comment by dobrynski** [comment]
Solved.. Uninstall all versions of the crypto library and reinstall pycryptodome.
It Will create a Crypto directory.
